# Name of website
title: Stellar-MADE project

# Your name to show in the footer
author: Nicolás Cuello

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


navbar-links:
  About: "https://nicolascuello.github.io/Stellar-MADE/about"
  Resources:
    - Stellar-MADE: "https://nicolascuello.github.io/Stellar-MADE/"
    - SANDS: "https://nicolascuello.github.io/SANDS/"
    - 4pi/360: "https://www.youtube.com/channel/UC1xIQfTHDtX2UrNhM-UVFRw"
  NC home: "https://nicolascuello.github.io/"

#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "nicolas.cuello@univ-grenoble-alpes.fr"
#  rss: true  # remove this line if you don't want to show an RSS link at the bottom
#  facebook: deanattali
  github: nicolascuello
  twitter: nomadastro
